openapi: 3.0.1
info:
  title: ApiDemo001
  description: ''
  version: '1.0'
servers:
  - url: https://apiops-demo-dev-apim.azure-api.net/apidemo001
paths:
  /session:
    get:
      summary: GetSession
      operationId: getsession
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]