openapi: 3.0.1
info:
  title: ApiDemo005
  description: ''
  version: '1.0'
servers:
  - url: https://apiops-demo-dev-apim.azure-api.net/apidemo005
paths:
  /talk:
    get:
      summary: get talk
      operationId: get-talk
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]