openapi: 3.0.1
info:
  title: ApiDemo002
  description: ''
  version: '1.0'
servers:
  - url: https://apiops-demo-dev-apim.azure-api.net/ApiDemo002
paths:
  /speakers:
    get:
      summary: get speakers
      description: get speakers
      operationId: get-speakers
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]